# OpenClaw Docker 热重载部署脚本 (Windows PowerShell)
# 基于官方 docker-setup.sh 改进，支持源代码热重载

param([switch]$Help)

$ErrorActionPreference = "Stop"

if ($Help) {
    Write-Host @"
OpenClaw Docker 热重载部署工具

用法：.\scripts\deploy-docker-hotreload.ps1

功能:
  - 构建支持热重载的本地 Docker 镜像
  - 配置命名卷以持久化用户数据
  - 挂载源代码目录以支持开发
  - 自动运行新手引导

管理命令:
  - 查看日志：docker compose logs -f openclaw-gateway
  - 重启服务：docker compose restart openclaw-gateway
  - 停止服务：docker compose down
  - 进入 CLI:  docker compose exec openclaw-cli node dist/index.js
"@
    exit 0
}

Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "OpenClaw Docker 热重载部署" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

# 检查 Docker
try {
    $dockerVersion = docker version --format "{{.Server.Version}}" 2>$null
    if (-not $dockerVersion) { throw "Docker not running" }
    Write-Host "[OK] Docker: $dockerVersion" -ForegroundColor Green
} catch {
    Write-Host "[ERROR] $_" -ForegroundColor Red
    exit 1
}

# 设置默认值
$env:OPENCLAW_CONFIG_DIR = if ($env:OPENCLAW_CONFIG_DIR) { $env:OPENCLAW_CONFIG_DIR } else { "$env:USERPROFILE\.openclaw" }
$env:OPENCLAW_WORKSPACE_DIR = if ($env:OPENCLAW_WORKSPACE_DIR) { $env:OPENCLAW_WORKSPACE_DIR } else { "$env:USERPROFILE\.openclaw\workspace" }
$env:OPENCLAW_GATEWAY_PORT = if ($env:OPENCLAW_GATEWAY_PORT) { $env:OPENCLAW_GATEWAY_PORT } else { "18789" }
$env:OPENCLAW_BRIDGE_PORT = if ($env:OPENCLAW_BRIDGE_PORT) { $env:OPENCLAW_BRIDGE_PORT } else { "18790" }
$env:OPENCLAW_GATEWAY_BIND = if ($env:OPENCLAW_GATEWAY_BIND) { $env:OPENCLAW_GATEWAY_BIND } else { "lan" }
$env:OPENCLAW_IMAGE = if ($env:OPENCLAW_IMAGE) { $env:OPENCLAW_IMAGE } else { "openclaw:local" }

# 热重载特定配置
$env:OPENCLAW_EXTRA_MOUNTS = if ($env:OPENCLAW_EXTRA_MOUNTS) { 
    $env:OPENCLAW_EXTRA_MOUNTS 
} else { 
    ".\src:/app/src:cached,.\extensions:/app/extensions:cached,.\packages:/app/packages:cached,.\ui:/app/ui:cached,.\skills:/app/skills:cached"
}

Write-Host "Configuration:" -ForegroundColor Yellow
Write-Host "  Config Dir: $($env:OPENCLAW_CONFIG_DIR)"
Write-Host "  Workspace: $($env:OPENCLAW_WORKSPACE_DIR)"
Write-Host "  Gateway Port: $($env:OPENCLAW_GATEWAY_PORT)"
Write-Host "  Gateway Bind: $($env:OPENCLAW_GATEWAY_BIND)"
Write-Host "  Image: $($env:OPENCLAW_IMAGE)"
Write-Host "  Hot Reload Mounts: $($env:OPENCLAW_EXTRA_MOUNTS)"
Write-Host ""

# 创建目录
New-Item -ItemType Directory -Force -Path $env:OPENCLAW_CONFIG_DIR | Out-Null
New-Item -ItemType Directory -Force -Path "$env:OPENCLAW_CONFIG_DIR\identity" | Out-Null
New-Item -ItemType Directory -Force -Path "$env:OPENCLAW_CONFIG_DIR\agents\main\agent" | Out-Null
New-Item -ItemType Directory -Force -Path "$env:OPENCLAW_CONFIG_DIR\agents\main\sessions" | Out-Null
New-Item -ItemType Directory -Force -Path $env:OPENCLAW_WORKSPACE_DIR | Out-Null

# 生成或复用 Token
$envFile = ".env.hotreload"
$token = $env:OPENCLAW_GATEWAY_TOKEN

if (-not $token) {
    $configFile = Join-Path $env:OPENCLAW_CONFIG_DIR "openclaw.json"
    if (Test-Path $configFile) {
        try {
            $config = Get-Content $configFile -Raw | ConvertFrom-Json
            $token = $config.gateway.auth.token
            Write-Host "[OK] Reusing existing Gateway Token" -ForegroundColor Green
        } catch {
            # Ignore
        }
    }
    
    if (-not $token) {
        $token = [System.BitConverter]::ToString((New-Object Security.Cryptography.SHA256Managed).ComputeHash([System.Text.Encoding]::UTF8.GetBytes([Guid]::NewGuid().ToString()))).Replace("-", "").ToLower()
        Write-Host "[OK] Generated new Gateway Token" -ForegroundColor Green
    }
} else {
    Write-Host "[OK] Using provided Gateway Token" -ForegroundColor Green
}

$env:OPENCLAW_GATEWAY_TOKEN = $token

# 写入 .env 文件
$envContent = @"
# OpenClaw Hot Reload Development Environment
# Auto-generated by deploy-docker-hotreload.ps1

OPENCLAW_CONFIG_DIR=$($env:OPENCLAW_CONFIG_DIR)
OPENCLAW_WORKSPACE_DIR=$($env:OPENCLAW_WORKSPACE_DIR)
OPENCLAW_GATEWAY_PORT=$($env:OPENCLAW_GATEWAY_PORT)
OPENCLAW_BRIDGE_PORT=$($env:OPENCLAW_BRIDGE_PORT)
OPENCLAW_GATEWAY_BIND=$($env:OPENCLAW_GATEWAY_BIND)
OPENCLAW_GATEWAY_TOKEN=$token
OPENCLAW_IMAGE=$($env:OPENCLAW_IMAGE)
OPENCLAW_EXTRA_MOUNTS=$($env:OPENCLAW_EXTRA_MOUNTS)
"@

Set-Content -Path $envFile -Value $envContent
Write-Host "[OK] Configuration written to $envFile" -ForegroundColor Green
Write-Host ""

# 构建镜像
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Building OpenClaw Image" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

$buildArgs = @()
if ($env:OPENCLAW_DOCKER_APT_PACKAGES) {
    $buildArgs += "--build-arg", "OPENCLAW_DOCKER_APT_PACKAGES=$env:OPENCLAW_DOCKER_APT_PACKAGES"
}
if ($env:OPENCLAW_EXTENSIONS) {
    $buildArgs += "--build-arg", "OPENCLAW_EXTENSIONS=$env:OPENCLAW_EXTENSIONS"
}
if ($env:OPENCLAW_INSTALL_DOCKER_CLI) {
    $buildArgs += "--build-arg", "OPENCLAW_INSTALL_DOCKER_CLI=$env:OPENCLAW_INSTALL_DOCKER_CLI"
}

$buildArgs += "-t", "$($env:OPENCLAW_IMAGE)"
$buildArgs += "-f", "Dockerfile"
$buildArgs += "."

docker build @buildArgs

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Build failed" -ForegroundColor Red
    exit 1
}

Write-Host "[OK] Image built: $($env:OPENCLAW_IMAGE)" -ForegroundColor Green
Write-Host ""

# 停止旧容器
Write-Host "Stopping existing containers..." -ForegroundColor Yellow
docker compose -f $envFile -f docker-compose.yml down --remove-orphans 2>&1 | Out-Null
Write-Host "[OK] Stopped" -ForegroundColor Green
Write-Host ""

# 运行新手引导
$configFile = Join-Path $env:OPENCLAW_CONFIG_DIR "openclaw.json"
if (-not (Test-Path $configFile)) {
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host "Running Onboarding" -ForegroundColor Cyan
    Write-Host "==========================================" -ForegroundColor Cyan
    Write-Host ""
    
    docker compose -f $envFile -f docker-compose.yml run --rm openclaw-cli onboard --mode local --no-install-daemon
    
    Write-Host "[OK] Onboarding complete" -ForegroundColor Green
    Write-Host ""
}

# 启动服务
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Starting OpenClaw Gateway" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

docker compose -f $envFile -f docker-compose.yml up -d openclaw-gateway

if ($LASTEXITCODE -ne 0) {
    Write-Host "[ERROR] Failed to start" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "Waiting for service to start..." -ForegroundColor Yellow
Start-Sleep -Seconds 10

# 健康检查
Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Service Status" -ForegroundColor Cyan
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""

docker compose -f $envFile -f docker-compose.yml ps

Write-Host ""
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host "Deployment Complete!" -ForegroundColor Green
Write-Host "==========================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "Access:" -ForegroundColor White
Write-Host "  - Gateway API: http://localhost:$($env:OPENCLAW_GATEWAY_PORT)" -ForegroundColor Cyan
Write-Host "  - Control UI: http://localhost:$($env:OPENCLAW_GATEWAY_PORT)/control-ui" -ForegroundColor Cyan
Write-Host "  - Gateway Token: $token" -ForegroundColor Cyan
Write-Host ""
Write-Host "Commands:" -ForegroundColor White
Write-Host "  - Logs: docker compose logs -f openclaw-gateway" -ForegroundColor Gray
Write-Host "  - Restart: docker compose restart openclaw-gateway" -ForegroundColor Gray
Write-Host "  - Stop: docker compose down" -ForegroundColor Gray
Write-Host "  - CLI: docker compose exec openclaw-cli node dist/index.js" -ForegroundColor Gray
Write-Host ""
Write-Host "Hot Reload:" -ForegroundColor White
Write-Host "  - After code changes, restart container to apply" -ForegroundColor Gray
Write-Host "  - Command: docker compose restart openclaw-gateway" -ForegroundColor Gray
Write-Host ""
Write-Host "Data Storage:" -ForegroundColor White
Write-Host "  - Config: $($env:OPENCLAW_CONFIG_DIR)" -ForegroundColor Gray
Write-Host "  - Workspace: $($env:OPENCLAW_WORKSPACE_DIR)" -ForegroundColor Gray
Write-Host ""
